@dominio = http://localhost:3000
@uid=1

### update usuario
POST {{dominio}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin2@admin2.es",
    "password": "admin2"
}

### get usuario
GET {{dominio}}/api/v1/usuarios/{{uid}}


### post de usuario
POST {{dominio}}/api/v1/usuarios
Content-Type: application/json

{
    "name": "admin1",
    "email": "email@admin1.es",
    "password": "12345678"
}