@dominio = http://localhost:3000
@uid=684ff5026158e631ec8e78d9

### logear usuario
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "email@admin3.es",
  "password": "123456789"
}


### get usuario
GET {{dominio}}/api/v1/usuarios/{{uid}}


### post de usuario
POST {{dominio}}/api/v1/usuarios
Content-Type: application/json

{
    "name": "userAdmin",
    "email": "email@admin3.es",
    "password": "123456789",
    "role" : "admin"
}